#!/bin/bash

# Script to chmod all files in a directory tree to 0644

walkdir() {
	cd "$@" || exit 
	for f in *; do
		if [[ -d "$f" ]]; then
			walkdir "$f"
		else
			chmod 0644 "$f"
		fi
	done
	cd .. || exit
}

walkdir "$@"
